#!/usr/bin/env bash

# VERSION = 0.0.3

# ╭──────────────────────────────────────────────────────────╮
# │ Variables                                                │
# ╰──────────────────────────────────────────────────────────╯
SLEEP_DURATION=0.04s
declare -a OPTIONS=(
	"Line0 - AssWipe"
	"Zeref - Everything Shape - Shape Clipper"
	"Zeref - Everything Shape - Shape to Clip"
	"Zeref - Everything Shape - Clip to Shape"
	"Zeref - Everything Shape - Expand"
	"PhosCity - svg2ass"
	"PhosCity - svg2ass - pasteover"
	"arch1t3cht - Note Browser - Load Notes"
	"arch1t3cht - Note Browser - Clear Markers"
	"petzku - Encode Clip"
	"Aegisub Motion - Apply"
	"Line0 - Merge Drawings"
	"Chrolo - Change Alignment"
	"Unanimated - Hyperdimensional Relocator - Round"
	"Unanimated - Hyperdimensional Relocator - Line2fbf"
	"Unanimated - Hyperdimensional Relocator - Find center"
	"Unanimated - Hyperdimensional Relocator - Align X"
	"Unanimated - Hyperdimensional Relocator - Align Y"
	"Unanimated - Hyperdimensional Relocator - clip2fax"
	"Unanimated - Hyperdimensional Relocator - clip2frz"
	"Unanimated - Script Cleanup - Remove Unused Styles"
	"Unanimated - HYDRA - Create 3D shadow"
	"Unanimated - HYDRA - fscx -> fscy"
	"Unanimated - HYDRA - fscy -> fscx"
	"Unanimated - HYDRA - Move color tag to first block"
	"Lyger - Lua Interpreter - Change ! to random character"
)

MISSING_DEPS=()
DEPENDENCIES=(rofi xdotool yad notify-send xclip)
SCRIPT_DIRECTORY=${BASH_SOURCE[0]%/*}
ROFI_THEME="${SCRIPT_DIRECTORY}/rofi-themes/window.rasi"
CACHE="${XDG_CACHE_HOME:-${HOME}/.cache}/aegisub-xdotool.txt"

# ╭──────────────────────────────────────────────────────────╮
# │ Functions                                                │
# ╰──────────────────────────────────────────────────────────╯

# Move mouse to ($1, $2) coordinate and left click
xdo() {
	sleep "${SLEEP_DURATION}"
	xdotool mousemove --sync "$1" "$2"
	xdotool click 1
}

# press a key $1 in the keyboard
key() {
	sleep "${SLEEP_DURATION}"
	xdotool key "$1"
}

# type $1 in the keyboard
type() {
	sleep "${SLEEP_DURATION}"
	xdotool type "$1"
}

# File selector. The extention of file is $1
select_file() {
	# Create cache file if it doesn't exist
	[[ -f "${CACHE}" ]] || echo "${HOME}" >"${CACHE}"
	DIR=$(cat "${CACHE}")
	[[ ! -d "${DIR}" ]] && DIR="${HOME}"
	cd "${DIR}" || exit 1

	FILETYPE="$1"
	FILE=$(yad --width 800 --height 500 --title "Choose ${FILETYPE} file" --file-filter "*.${FILETYPE}" --file)
	if [[ ${FILE##*.} != "${FILETYPE}" ]]; then
		notify-send "${FILETYPE} file was not selected."
		exit 1
	else
		NEW_DIR=$(dirname "${FILE}")
		echo "${NEW_DIR}" >"${CACHE}"
	fi
}

# ╭──────────────────────────────────────────────────────────╮
# │ Repeatedly used Aegisub Scripts                          │
# ╰──────────────────────────────────────────────────────────╯

# ASSWipe
asswipe() {
	sleep 0.8s
	xdo 323 51  # Click on Automation Menu
	xdo 329 104 # Click on line0
	xdo 519 101 # Click on ASSWipe
	xdo 531 619 # Click on OK Button
	sleep 1s    # Allow 1 second for asswipe to complete. If processing takes more than that, close manually
	xdo 686 311 # Click on Close Button
}

# Open Everything Shape Script
open_everything_shape() {
	xdo 331 47  # Click on Automation Tab
	xdo 328 276 # Click on !Zeref
	xdo 494 279 # Click on Everything Shape
	xdo 634 279 # Click on Everything Shape
}

# Shape Expand - Zeref's Everything Shape
expand_shape() {
	open_everything_shape
	xdo 585 247 # Click on dropdown for all all modes
	xdo 514 357 # Click on Shape Expand
	xdo 475 556 # Click on `Shape` Button
}

# Open Hyperdimensional Relocator
open_relocator() {
	xdo 326 48  # Click on Automation
	xdo 332 227 # Click on !unanimated
	xdo 557 380 # Click on Hyperdimensional Relocator
}

# Round the tags using Hyperdimensional Relocator
round_tags() {
	open_relocator
	xdo 724 285 # Click on Metamorphosis dropdown
	xdo 666 82  # Click on round numbers
	xdo 714 356 # Click on round dropdown
	case "$1" in
		0.1) xdo 667 415 ;;
		0.01) xdo 670 440 ;;
		0.001) xdo 670 470 ;;
		1 | *) xdo 660 390 ;;
	esac
	xdo 620 505 # Click on Metamorphosis Button
}

# Open Unanimated - HYDRA
open_hydra() {
	xdo 329 50  # Click on Automation
	xdo 346 229 # Click on !unanimated
	xdo 532 351 # Click on Hydra
}

# ╭──────────────────────────────────────────────────────────╮
# │ Check for dependencies                                   │
# ╰──────────────────────────────────────────────────────────╯
for i in "${DEPENDENCIES[@]}"; do
	if ! command -v "${i}" >/dev/null; then
		MISSING_DEPS+=("${i}")
	fi
done
if [[ "${#MISSING_DEPS}" -gt 0 ]]; then
	printf -v missing_deps '%s, ' "${MISSING_DEPS[@]}"
	echo "${missing_deps%, } not found. Please install all missing dependencies."
	notify-send "${missing_deps%, } not found. Please install all missing dependencies."
	exit 1
fi

# ╭──────────────────────────────────────────────────────────╮
# │ Main                                                     │
# ╰──────────────────────────────────────────────────────────╯
PLUGIN_NAME=$(printf '%s\n' "${OPTIONS[@]}" | rofi -dmenu -i -p "Plugins:" -theme "${ROFI_THEME}")

case "${PLUGIN_NAME}" in
	"Line0 - AssWipe") asswipe ;;

	"Zeref - Everything Shape - Shape Clipper")
		# Shape clipping sometimes gives wrong results so it's recommended that you expand the shape first
		expand_shape
		open_everything_shape
		xdo 585 247 # Click on dropdown for all all modes
		xdo 490 332 # Click on Shape Clipper
		xdo 475 556 # Click on `Shape` Button
		asswipe
		;;

	"Zeref - Everything Shape - Shape to Clip")
		expand_shape
		open_everything_shape
		xdo 585 247 # Click on dropdown for all all modes
		xdo 512 580 # Click on Shape to Clip
		xdo 475 556 # Click on `Shape` Button
		;;

	"Zeref - Everything Shape - Clip to Shape")
		open_everything_shape
		xdo 585 247 # Click on dropdown for all all modes
		xdo 488 281 # Click on clip to shape
		xdo 475 556 # Click on `Shape` Button
		asswipe
		;;

	"Zeref - Everything Shape - Expand")
		expand_shape
		asswipe
		;;

	"PhosCity - svg2ass" | "PhosCity - svg2ass - pasteover")
		MODE=$(printf "drawing\nclip\niclip" | rofi -dmenu -i -p "Mode:" -theme "${ROFI_THEME}")

		select_file "svg"
		PATH_TO_SVG2ASS="${HOME}/Fansubbing/Scripts/svg2ass" # where svg2ass is located (If svg2ass is at path, remove this line and replace this variable with `svg2ass` below)
		"${PATH_TO_SVG2ASS}" "${FILE}" | xclip -selection clipboard

		xdo 331 47  # Click on Automation Tab
		xdo 327 200 # Click on !phoscity
		xdo 536 451 # Click on svg2ass
		xdo 680 478 # Click on run
		case "${MODE}" in
			"clip")
				xdo 509 427 # Untick drawing
				xdo 614 423 # Tick clip
				;;
			"iclip")
				xdo 509 427 # Untick drawing
				xdo 682 426 # Tick iclip
				;;
			*) ;;
		esac
		if [[ "${PLUGIN_NAME}" == "PhosCity - svg2ass - pasteover" ]]; then
			xdo 767 431 # Tick `pasteover`
		fi
		xdo 680 320 # Click inside the textbox
		key ctrl+a  # Select everything inside the textbox
		key ctrl+v  # Paste whatever's on clipboard to the textbox
		xdo 625 455 # Click on `Textbox` button
		asswipe
		;;

	"arch1t3cht - Note Browser - Load Notes")
		select_file "txt"
		xclip -selection clipboard -i <"${FILE}"

		xdo 331 47  # Click on Automation Tab
		xdo 355 160 # Click on !pace
		xdo 555 180 # Click on Note Browser
		xdo 730 300 # Click on Load Notes
		xdo 520 310 # Click on text box
		key ctrl+v  # Paste whatever's on clipboard to the textbox
		xdo 590 515 # Click on Ok button
		;;

	"arch1t3cht - Note Browser - Clear Markers")
		xdo 331 47  # Click on Automation Tab
		xdo 355 160 # Click on !pace
		xdo 555 180 # Click on Note Browser
		;;

	"petzku - Encode Clip")
		MODE=$(printf "Clip with Subtitles\nClip with Subtitles (No Audio)\nRaw Video\nRaw Video (No Audio)\nAudio Only" | rofi -dmenu -i -p "Mode:" -theme "${ROFI_THEME}")

		xdo 331 47  # Click on Automation Tab
		xdo 355 185 # Click on !petzku
		xdo 537 201 # Click on Encode Clip
		case "${MODE}" in
			"Clip with Subtitles") xdo 700 280 ;;
			"Clip with Subtitles (No Audio)") xdo 700 300 ;;
			"Raw Video") xdo 700 240 ;;
			"Raw Video (No Audio)") xdo 700 253 ;;
			"Audio Only") xdo 700 215 ;;
			*) ;;
		esac
		;;

	"Aegisub Motion - Apply")
		select_file "txt"
		xclip -selection clipboard -i <"${FILE}"
		xdo 331 47  # Click on Automation Tab
		xdo 390 352 # Click on Aegisub Motion
		xdo 534 355 # Click on Apply
		xdo 600 273 # Click on the texbox
		key ctrl+v
		xdo 533 520 # Click on Go button
		;;

	"Line0 - Merge Drawings")
		# Merge drawings tend to give wrong results when fscx/y != 100
		xdo 324 52  # Click on Automation
		xdo 336 103 # Click on !line0
		xdo 532 149 # Click on Merge Drawings
		xdo 772 332 # Click on alignment dropdown
		xdo 705 536 # Click on 7
		xdo 734 367 # Click on Scale x
		key ctrl+a
		type 100
		xdo 738 399 # Click on Scale y
		key ctrl+a
		type 100
		xdo 730 436 # Click on OK Button
		asswipe
		;;

	"Chrolo - Change Alignment")
		ALIGNMENT=$(seq 1 9 | rofi -dmenu -i -p "Mode:" -theme "${ROFI_THEME}")
		xdo 322 45  # Click on Automation
		xdo 345 251 # Click on !utilities
		xdo 537 304 # Click on Chrolo
		xdo 706 301 # Click on Change Alignment
		xdo 663 383 # Click on dropdown
		case "${ALIGNMENT}" in
			1) xdo 602 409 ;;
			2) xdo 608 438 ;;
			3) xdo 600 459 ;;
			4) xdo 609 496 ;;
			5) xdo 602 520 ;;
			6) xdo 606 549 ;;
			7) xdo 598 577 ;;
			8) xdo 601 605 ;;
			9) xdo 604 632 ;;
			*) ;;
		esac
		xdo 728 414 # Click on Switch
		round_tags 0.001
		;;

	"Unanimated - Hyperdimensional Relocator - Round")
		PRECISION=$(printf "1\n0.1\n0.01\n0.001" | rofi -dmenu -i -p "Mode:" -theme "${ROFI_THEME}")
		round_tags "${PRECISION}"
		;;

	"Unanimated - Hyperdimensional Relocator - Line2fbf")
		open_relocator
		xdo 724 285 # Click on Metamorphosis dropdown
		xdo 641 108 # Click on line2fbf
		xdo 620 505 # Click on Metamorphosis Button
		;;

	"Unanimated - Hyperdimensional Relocator - Find center")
		open_relocator
		xdo 724 285 # Click on Metamorphosis dropdown
		xdo 650 499 # Click on find centre
		xdo 620 505 # Click on Metamorphosis Button
		;;

	"Unanimated - Hyperdimensional Relocator - Align X")
		open_relocator
		xdo 463 292 # Click on Positron Canon dropdown
		xdo 405 163 # Click on Align X
		xdo 382 502 # Click on Positron Canon Button
		;;

	"Unanimated - Hyperdimensional Relocator - Align Y")
		open_relocator
		xdo 463 292 # Click on Positron Canon dropdown
		xdo 365 193 # Click on Align Y
		xdo 382 502 # Click on Positron Canon Button
		;;

	"Unanimated - Hyperdimensional Relocator - clip2fax")
		open_relocator
		xdo 463 292 # Click on Positron Canon dropdown
		xdo 385 248 # Click on clip to fax
		xdo 382 502 # Click on Positron Canon Button
		;;

	"Unanimated - Hyperdimensional Relocator - clip2frz")
		open_relocator
		xdo 463 292 # Click on Positron Canon dropdown
		xdo 405 274 # Click on clip to frz
		xdo 382 502 # Click on Positron Canon Button
		;;

	"Unanimated - Script Cleanup - Remove Unused Styles")
		xdo 327 48  # Click on Automation
		xdo 332 227 # Click on !unanimated
		xdo 554 680 # Click on Script Cleanup
		xdo 536 431 # Click on Tick 'Delete unused styles'
		xdo 387 537 # Click on 'Run Selected' Button
		;;

	"Unanimated - HYDRA - Create 3D shadow")
		open_hydra
		xdo 881 590 # Click on 'special' dropdown
		xdo 745 393 # Click on create 3D shadow
		xdo 717 662 # Click on Special Button
		;;

	"Unanimated - HYDRA - fscx -> fscy")
		open_hydra
		xdo 881 590 # Click on 'special' dropdown
		xdo 720 171 # Click on fscx -> fscy
		xdo 717 662 # Click on Special Button
		;;

	"Unanimated - HYDRA - fscy -> fscx")
		open_hydra
		xdo 881 590 # Click on 'special' dropdown
		xdo 706 201 # Click on fscy -> fscx
		xdo 717 662 # Click on Special Button
		;;

	"Unanimated - HYDRA - Move color tag to first block")
		open_hydra
		xdo 881 590 # Click on 'special' dropdown
		xdo 756 448 # Click on move color tag to first block
		xdo 717 662 # Click on Special Button
		;;

	"Lyger - Lua Interpreter - Change ! to random character")
		xdo 327 51  # Click on Automation
		xdo 339 127 # Click on !lyger
		xdo 542 226 # Click on lua interpreter
		xdo 675 440 # Click on snippet dropdown
		xdo 466 531 # Click on change ! to random character
		xdo 536 473 # Click on Load Button
		xdo 452 474 # Click on Run Button
		;;

	*) ;;
esac
