#!/usr/bin/env bash

# VERSION = 0.0.3

# ╭──────────────────────────────────────────────────────────╮
# │ Variables                                                │
# ╰──────────────────────────────────────────────────────────╯
SLEEP_DURATION=0.04s # [EDIT] Increase this value if the script executes so fast that it's missing what it should click.

# [EDIT] Write the names of the plugins here by replacing "items" below
declare -a OPTIONS=(
	"item1"
	"item2"
)

MISSING_DEPS=()
DEPENDENCIES=(rofi xdotool yad notify-send xclip)
SCRIPT_DIRECTORY=${BASH_SOURCE[0]%/*}
ROFI_THEME="${SCRIPT_DIRECTORY}/rofi-themes/window.rasi"
CACHE="${XDG_CACHE_HOME:-${HOME}/.cache}/aegisub-xdotool.txt"

# ╭──────────────────────────────────────────────────────────╮
# │ Functions                                                │
# ╰──────────────────────────────────────────────────────────╯

# Move mouse to ($1, $2) coordinate and left click
xdo() {
	sleep "${SLEEP_DURATION}"
	xdotool mousemove --sync "$1" "$2"
	xdotool click 1
}

# type key $1 in the keyboard
key() {
	sleep "${SLEEP_DURATION}"
	xdotool key "$1"
}

# File selector. The extention of file is $1
select_file() {
	# Create cache file if it doesn't exist
	[[ -f "${CACHE}" ]] || echo "${HOME}" >"${CACHE}"
	DIR=$(cat "${CACHE}")
	[[ ! -d "${DIR}" ]] && DIR="${HOME}"
	cd "${DIR}" || exit 1

	FILETYPE="$1"
	FILE=$(yad --width 800 --height 500 --title "Choose ${FILETYPE} file" --file-filter "*.${FILETYPE}" --file)
	if [[ ${FILE##*.} != "${FILETYPE}" ]]; then
		notify-send "${FILETYPE} file was not selected."
		exit 1
	else
		NEW_DIR=$(dirname "${FILE}")
		echo "${NEW_DIR}" >"${CACHE}"
	fi
}

# ╭──────────────────────────────────────────────────────────╮
# │ Check for dependencies                                   │
# ╰──────────────────────────────────────────────────────────╯
for i in "${DEPENDENCIES[@]}"; do
	if ! command -v "${i}" >/dev/null; then
		MISSING_DEPS+=("${i}")
	fi
done
if [[ "${#MISSING_DEPS}" -gt 0 ]]; then
	printf -v missing_deps '%s, ' "${MISSING_DEPS[@]}"
	echo "${missing_deps%, } not found. Please install all missing dependencies."
	notify-send "${missing_deps%, } not found. Please install all missing dependencies."
	exit 1
fi

# ╭──────────────────────────────────────────────────────────╮
# │ Main                                                     │
# ╰──────────────────────────────────────────────────────────╯
PLUGIN_NAME=$(printf '%s\n' "${OPTIONS[@]}" | rofi -dmenu -i -p "Plugins:" -theme "${ROFI_THEME}")

case "${PLUGIN_NAME}" in
	"item1")
		# [EDIT] Put xdotool commands to execute plugin item1 here
		;;
	"item2")
		# [EDIT] Put xdotool commands to execute plugin item2 here
		;;
	*) ;;
esac
